---
title: "Groupwork(Jialin, Ruiling, Qimiao"
author: "CrazyFriday"
date: "2025-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(openxlsx)
library(here)
library(dplyr)
```

## Loading data

```{r cars}

df1 <- read.xlsx(here("A.xlsx"))
df2 <- read.xlsx(here("B.xlsx"))
df3 <- read.xlsx(here("H.xlsx"))
df4 <- read.xlsx(here("P.xlsx"))
df5 <- read.xlsx(here("SouthEast.xlsx"))

str(df1)
str(df3)
str(df4)
str(df5)

target_cols <- c("Age", "Region", "PH", "MH", "Smoker", "Belief", "SES5", "Gender")

df3 <- df3 %>%
  rename(
    PH = Physical,
    MH = Mental
  ) %>%
  mutate(
    SES5 = NA,   # does not exist in df3
    Name = NULL  # remove unwanted column
  ) %>%
  select(all_of(target_cols))

df5 <- df5 %>%
  rename(
    PH = Phusical,   # fix misspelling
    MH = Mental
  ) %>%
  mutate(
    ID = NULL       # remove
  ) %>%
  select(all_of(target_cols))
all_data <- bind_rows(df1, df2, df3, df4, df5)

all_data <- all_data %>%
  mutate(
    Gender = tolower(Gender),   # standardize to lower case
    Gender = case_when(
      Gender %in% c("f", "female") ~ "Female",
      Gender %in% c("m", "male")     ~ "Male",
      Gender %in% c("gd")     ~ "GD",
      is.na(Gender)                         ~ NA_character_,  # leave NA unchanged
      TRUE                         ~ NA_character_        # all other values
    )
  )
all_data <- all_data %>%
  mutate(
    Smoker = case_when(
      Smoker == "Current" ~ "Y",
      TRUE                ~ Smoker   # keep Y, No, NA, etc. as they are
    )
  )


all_data <- all_data %>%
  mutate(
    # categorical yes/no variables
    PH     = factor(PH,     levels = c("N", "Y")),
    MH     = factor(MH,     levels = c("N", "Y")),
    Belief = factor(Belief, levels = c("N", "Y")),

    # smoker variable
    Smoker = factor(Smoker, levels = c("N", "Y")),

    # SES ordered factor
    SES5 = factor(SES5, levels = c("L1", "L2", "L3", "L4", "L5")),

    # gender categories
    Gender = factor(Gender, levels = c("Female", "Male", "GD")),

    # region (auto or manual)
    Region = factor(Region)
  )

all_data <- all_data %>%
  mutate(
    # categorical yes/no variables
    PH     = factor(PH,     levels = c("N", "Y")),
    MH     = factor(MH,     levels = c("N", "Y")),
    Belief = factor(Belief, levels = c("N", "Y")),

    # smoker variable
    Smoker = factor(Smoker, levels = c("N", "Y")),

    # SES ordered factor
    SES5 = factor(SES5, levels = c("L1", "L2", "L3", "L4", "L5")),

    # gender categories
    Gender = factor(Gender, levels = c("Female", "Male", "GD")),

    # region (auto or manual levels)
    Region = factor(Region)
  )
## ageband

all_data$AgeBand <- cut(
  all_data$Age,
  breaks = c(-Inf, 10, 20, 30, 40, 50, 60, 70, Inf),
  labels = 1:8,
  right = TRUE
)
summary(all_data)

```

```{r}
## Merge PH & MH

all_data$Health_issues <- ifelse(all_data$PH == "Y" | all_data$MH == "Y", 1, 0)
all_data$Belief_new <- ifelse(all_data$Belief == "Y", 1, 0)
```

## Glm Belief~Health_issue
```{r}
model <- glm(Belief_new ~ Health_issues, family = "binomial", data = all_data)
summary(model)
```
## Glm + confounders 
```{r}
model <- glm(Belief_new ~ Health_issues + Smoker + SES5 + Gender + Region, family = "binomial", data = all_data)
summary(model)
```
## Adjusted prevelence

```{r cars}

str(all_data)
model <- glm(Health_issues ~ Age +Smoker+ Belief + SES5 +Gender+Region, data = all_data, family = binomial)
summary(model)## +Region
predict_prob <- predict(model, type = "response")
adjusted_prevalence <- mean(predict_prob)
adjusted_prevalence

```
## Validate representiveness
```{r cars}
POP <- readRDS("POP.rds")
class(POP)  
str(POP)    
head(POP)  
View(POP)

table(all_data$Gender) / nrow(all_data)
table(POP$Gender) / nrow(POP)

tab1 <- rbind(
  all_data = table(all_data$Gender),
  POP = table(POP$Gender)
)
chisq.test(tab1)


table(all_data$Region) / nrow(all_data)
table(POP$Region) / nrow(POP)

tab2 <- rbind(
  all_data = table(all_data$Region),
  POP = table(POP$Region)
)
chisq.test(tab2)



table(all_data$SES5) / nrow(all_data)
table(POP$SES) / nrow(POP)

tab3 <- rbind(
  all_data = table(all_data$SES5),
  POP = table(POP$SES)
)
chisq.test(tab3)


table(all_data$AgeBand) / nrow(all_data)
table(POP$AgeBand) / nrow(POP)

tab4 <- rbind(
  all_data = table(all_data$AgeBand),
  POP = table(POP$AgeBand)
)
chisq.test(tab4)

```

